import Head from "next/head";
import styles from "../styles/Home.module.css";
import CssBaseline from "@mui/material/CssBaseline";

import FormTest1 from "../components/formTest1/formTest1";
import FormTest2 from "../components/formTest2/formTest2";
import FormTest3 from "../components/formTest3/formTest3";

export default function Home() {
  return (
    <div className={styles.container}>
      <CssBaseline />
      <Head>
        <title>React practice</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className={styles.mainTitle}>MUI + Yup + react-hook-form</h1>
        <FormTest1 />
        <FormTest2 />
        <FormTest3 />
      </main>
    </div>
  );
}
